/*
 * Clarify.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/06/2014
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Clarify.PCL;

namespace Clarify.PCL.Models
{
    public class ClarifyTracksModel : ClarifyBaseModel 
    {
        // These fields hold the values for the public properties.
        private List<TracksModel> tracks;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("tracks")]
        public List<TracksModel> Tracks 
        { 
            get 
            {
                return this.tracks; 
            } 
            set 
            {
                this.tracks = value;
                onPropertyChanged("Tracks");
            }
        }
    }
} 