/*
 * Clarify.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/06/2014
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Clarify.PCL;

namespace Clarify.PCL.Models
{
    public class GetBundleResponseModel : BaseClassLinkModel 
    {
        // These fields hold the values for the public properties.
        private string id;
        private int version;
        private string name;
        private string externalId;
        private string notifyUrl;
        private string created;
        private string updated;
        private string mClass;
        private LinksBaseModel mLinks;
        private EmbededModel mEmbedded;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id ")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("version")]
        public int Version 
        { 
            get 
            {
                return this.version; 
            } 
            set 
            {
                this.version = value;
                onPropertyChanged("Version");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("external_id")]
        public string ExternalId 
        { 
            get 
            {
                return this.externalId; 
            } 
            set 
            {
                this.externalId = value;
                onPropertyChanged("ExternalId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("notify_url")]
        public string NotifyUrl 
        { 
            get 
            {
                return this.notifyUrl; 
            } 
            set 
            {
                this.notifyUrl = value;
                onPropertyChanged("NotifyUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("created")]
        public string Created 
        { 
            get 
            {
                return this.created; 
            } 
            set 
            {
                this.created = value;
                onPropertyChanged("Created");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("updated")]
        public string Updated 
        { 
            get 
            {
                return this.updated; 
            } 
            set 
            {
                this.updated = value;
                onPropertyChanged("Updated");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("_class")]
        public string MClass 
        { 
            get 
            {
                return this.mClass; 
            } 
            set 
            {
                this.mClass = value;
                onPropertyChanged("MClass");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("_links")]
        public LinksBaseModel MLinks 
        { 
            get 
            {
                return this.mLinks; 
            } 
            set 
            {
                this.mLinks = value;
                onPropertyChanged("MLinks");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("_embedded")]
        public EmbededModel MEmbedded 
        { 
            get 
            {
                return this.mEmbedded; 
            } 
            set 
            {
                this.mEmbedded = value;
                onPropertyChanged("MEmbedded");
            }
        }
    }
} 