/*
 * Clarify.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/06/2014
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Clarify.PCL;

namespace Clarify.PCL.Models
{
    public class Link3Model : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string self;
        private string curies;
        private string parent;
        private string clarifyBundle;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("self")]
        public string Self 
        { 
            get 
            {
                return this.self; 
            } 
            set 
            {
                this.self = value;
                onPropertyChanged("Self");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("curies")]
        public string Curies 
        { 
            get 
            {
                return this.curies; 
            } 
            set 
            {
                this.curies = value;
                onPropertyChanged("Curies");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("parent")]
        public string Parent 
        { 
            get 
            {
                return this.parent; 
            } 
            set 
            {
                this.parent = value;
                onPropertyChanged("Parent");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("clarify:bundle")]
        public string ClarifyBundle 
        { 
            get 
            {
                return this.clarifyBundle; 
            } 
            set 
            {
                this.clarifyBundle = value;
                onPropertyChanged("ClarifyBundle");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 