/*
 * Clarify.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/06/2014
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Clarify.PCL;

namespace Clarify.PCL.Models
{
    public class TracksModel : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string id;
        private string track;
        private string label;
        private string mediaUrl;
        private string audioChannel;
        private string created;
        private string updated;
        private string status;
        private string mimeType;
        private string mediaSize;
        private string duration;
        private int fetchResponseCode;
        private string fetchResponseMessage;
        private int mediaCode;
        private string mediaMessage;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("track")]
        public string Track 
        { 
            get 
            {
                return this.track; 
            } 
            set 
            {
                this.track = value;
                onPropertyChanged("Track");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("label")]
        public string Label 
        { 
            get 
            {
                return this.label; 
            } 
            set 
            {
                this.label = value;
                onPropertyChanged("Label");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("media_url")]
        public string MediaUrl 
        { 
            get 
            {
                return this.mediaUrl; 
            } 
            set 
            {
                this.mediaUrl = value;
                onPropertyChanged("MediaUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("audio_channel")]
        public string AudioChannel 
        { 
            get 
            {
                return this.audioChannel; 
            } 
            set 
            {
                this.audioChannel = value;
                onPropertyChanged("AudioChannel");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("created")]
        public string Created 
        { 
            get 
            {
                return this.created; 
            } 
            set 
            {
                this.created = value;
                onPropertyChanged("Created");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("updated")]
        public string Updated 
        { 
            get 
            {
                return this.updated; 
            } 
            set 
            {
                this.updated = value;
                onPropertyChanged("Updated");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("status")]
        public string Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("mime_type")]
        public string MimeType 
        { 
            get 
            {
                return this.mimeType; 
            } 
            set 
            {
                this.mimeType = value;
                onPropertyChanged("MimeType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("media_size")]
        public string MediaSize 
        { 
            get 
            {
                return this.mediaSize; 
            } 
            set 
            {
                this.mediaSize = value;
                onPropertyChanged("MediaSize");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("duration")]
        public string Duration 
        { 
            get 
            {
                return this.duration; 
            } 
            set 
            {
                this.duration = value;
                onPropertyChanged("Duration");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fetch_response_code")]
        public int FetchResponseCode 
        { 
            get 
            {
                return this.fetchResponseCode; 
            } 
            set 
            {
                this.fetchResponseCode = value;
                onPropertyChanged("FetchResponseCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fetch_response_message")]
        public string FetchResponseMessage 
        { 
            get 
            {
                return this.fetchResponseMessage; 
            } 
            set 
            {
                this.fetchResponseMessage = value;
                onPropertyChanged("FetchResponseMessage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("media_code")]
        public int MediaCode 
        { 
            get 
            {
                return this.mediaCode; 
            } 
            set 
            {
                this.mediaCode = value;
                onPropertyChanged("MediaCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("media_message")]
        public string MediaMessage 
        { 
            get 
            {
                return this.mediaMessage; 
            } 
            set 
            {
                this.mediaMessage = value;
                onPropertyChanged("MediaMessage");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 