/*
 * Clarify.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 10/06/2014
 */
using System;

namespace Clarify.PCL
{
    public class Configuration
    {
        //The base Uri for API calls
        public const string BaseUri = "https://api.clarify.io/v1";

        //The OAuth 2.0 access token to be set before API calls
        //TODO: Replace the OAuthAccessToken with an appropriate value
        public static string OAuthAccessToken = "TODO: Replace";

    }
}